create table CUSTOMERS(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
name varchar,
surname varchar,
age int,
phone_number varchar
);

create table ORDERS(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
date varchar,
customer_id  int references customers (id),
product_name varchar,
amount int
);

